@startuml Diagrama de Sequência
title Executar Simulação
autonumber 1.1.1

Pesquisador -> Navegador: Solicitar a execução\n de uma simulação
Navegador -> Experimenter: POST /rodada
Experimenter -> Database: novaRodada(Versão)
Database --> ProvenanceCatcher: rodadaID
ProvenanceCatcher --> Experimenter: rodadaID

autonumber inc B
Experimenter -> Experimenter: GET /rodada/[rodadaID]
Experimenter -> Experimenter: checarStatusRodada(rodadaID)
Experimenter -> ExperimentsConfigurator: getConfiguração(rodadaID)
ExperimentsConfigurator --> Experimenter: Configuração do Experimento
Experimenter -> Experimenter: colocar experimento na fila
Experimenter --> Navegador: Páginda de execução de Experimento (HTML e JS)
Navegador -> Navegador: Renderizar Página
Navegador -> Pesquisador: Exibir Página de Rodada(Em execução)

autonumber inc B
Navegador -> Experimenter: abrir conexão websocket
Experimenter --> Navegador: conexão websocket estabelecida
note over Experimenter: Quando o experimento em questão estiver no topo da fila.
Experimenter -> Experimenter: consumir fila de experimento
Experimenter -> MininetWifiAdapter: solicitar inicialização do experimento
MininetWifiAdapter -> MininetWifi: inicializar experimento
loop Até a Solicitação de encerrar Rodada
    MininetWifi -> MininetWifiAdapter: resultado parcial
    MininetWifiAdapter -> Experimenter: resultado parcial
    MininetWifiAdapter -> ProvenanceCatcher: resultado parcial
    ProvenanceCatcher -> ProvenanceCatcher: armazenar resultado parcial
    Experimenter -> Navegador: Resultado Parcial (via webSocket)
    Navegador -> Pesquisador: Exibir Resultado Parcial
end

autonumber inc A
Pesquisador -> Navegador: Solicita finalização do experimento
Navegador -> Experimenter: POST /encerrar-rodada/[rodadaID]
Experimenter -> MininetWifiAdapter: solicitar finalização do experimento
MininetWifiAdapter --> Experimenter: experimento finalizado
Experimenter -> ProvenanceCatcher: salvarResultado(Rodada)
ProvenanceCatcher -> Database: novoResultado()
Database --> ProvenanceCatcher: OK
ProvenanceCatcher --> Experimenter: OK
Experimenter --> Navegador: OK

autonumber inc B
Navegador -> Experimenter: encerrar conexão websocket

autonumber inc B
Navegador -> Experimenter: GET /rodada/[rodadaID]
Experimenter -> ProvenanceCatcher: checarStatusRodada(rodadaID)
ProvenanceCatcher --> Experimenter: Status da Rodada
Experimenter -> ProvenanceCatcher: getConfiguração(rodadaID)
ProvenanceCatcher --> Experimenter: Configuração do Experimento
Experimenter -> ProvenanceCatcher: getResultado(rodadaID)
ProvenanceCatcher --> Experimenter: Resultado do Experimento
Experimenter --> Navegador: Páginaa de vizualização de Experimento (HTML e JS)
Navegador -> Navegador: Renderizar Página
Navegador -> Pesquisador: Exibir Página de Rodada(Finalizada)




@enduml