# Generated by Django 3.2.6 on 2021-09-19 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicao_schema', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fix', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freq', models.IntegerField()),
                ('fix', models.BooleanField()),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configurator.configuration')),
                ('measure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configurator.measure')),
            ],
        ),
        migrations.AddField(
            model_name='configuration',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configurator.network'),
        ),
    ]
