# Generated by Django 3.2.6 on 2021-10-02 13:11

from __future__ import unicode_literals
from django.db import migrations, models

def insert_mobility_model_catalog(apps, schema_editor):
    MM_MODELS = [
        {"name": "RandomDirection", "displayname": "Direction"}
    ]


    MModelCatalog = apps.get_model("configurator", "MModelCatalog")
    for mm in MM_MODELS:
        catalogItem = MModelCatalog(**mm)
        catalogItem.save()

def insert_propagation_model_catalog(apps, schema_editor):
    PM_MODELS = [
        {"name": "logDistance", "displayname": "Log Distance"},
        {"name": "friis", "displayname": "Free Space"}
    ]


    PModelCatalog = apps.get_model("configurator", "PModelCatalog")
    for pm in PM_MODELS:
        catalogItem = PModelCatalog(**pm)
        catalogItem.save()

class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_mobility_model_catalog),
        migrations.RunPython(insert_propagation_model_catalog),
    ]
