# Generated by Django 3.2.6 on 2021-10-14 02:53

from __future__ import unicode_literals
from django.db import migrations, models

def insert_mobility_model_catalog(apps, schema_editor):
    MM_MODELS = [
        {"name": "RandomDirection", "displayname": "Random Direction"}
    ]


    MModelCatalog = apps.get_model("configurator", "MModelCatalog")
    for mm in MM_MODELS:
        catalogItem = MModelCatalog(**mm)
        catalogItem.save()

def insert_propagation_model_catalog(apps, schema_editor):
    PM_MODELS = [
        {"name": "logDistance", "displayname": "Log Distance"},
        {"name": "friis", "displayname": "Free Space"}
    ]


    PModelCatalog = apps.get_model("configurator", "PModelCatalog")
    for pm in PM_MODELS:
        catalogItem = PModelCatalog(**pm)
        catalogItem.save()

def insert_rfmeasure_catalog(apps, schema_editor):
    measures = [
        {"name": "rssi", "unit": ""},
        {"name": "channel", "unit": ""},
        {"name": "band", "unit": ""},
        {"name": "txpower", "unit": ""},
        {"name": "ip", "unit": ""},
        {"name": "position", "unit": ""},
        {"name": "associatedTo", "unit": ""}
    ]

    Measure = apps.get_model("configurator", "Measure")
    for measure in measures:
        catalogItem = Measure(**measure)
        catalogItem.save()

def insert_pmeasure_catalog(apps, schema_editor):
    measures = [
        {"name": "ping", "unit": ""}
    ]

    Measure = apps.get_model("configurator", "PerformanceMeasure")
    for measure in measures:
        catalogItem = Measure(**measure)
        catalogItem.save()


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_mobility_model_catalog),
        migrations.RunPython(insert_propagation_model_catalog),
        migrations.RunPython(insert_rfmeasure_catalog),
        migrations.RunPython(insert_pmeasure_catalog),
    ]
