# Generated by Django 3.2.6 on 2021-09-21 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='network',
        ),
        migrations.AddField(
            model_name='measure',
            name='unit',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Network',
        ),
    ]
