# Generated by Django 3.2.6 on 2021-10-02 13:11

from __future__ import unicode_literals
from django.db import migrations, models

def insert_measure_catalog(apps, schema_editor):
    measures = [
        {"name": "rssi", "unit": ""},
        {"name": "channel", "unit": ""},
        {"name": "band", "unit": ""},
        {"name": "txpower", "unit": ""},
        {"name": "ip", "unit": ""},
        {"name": "position", "unit": ""},
        {"name": "associatedTo", "unit": ""}
    ]

    Measure = apps.get_model("configurator", "Measure")
    for measure in measures:
        catalogItem = Measure(**measure)
        catalogItem.save()

class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0002_auto_20211002_1311'),
    ]

    operations = [
        migrations.RunPython(insert_measure_catalog)
    ]
