# Generated by Django 3.2.6 on 2021-10-14 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0002_auto_20211014_0253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='switch',
            name='type',
        ),
    ]
