# Generated by Django 3.2.6 on 2021-09-21 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0002_auto_20210921_0358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='freq',
            new_name='period',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='fix',
        ),
    ]
