# Generated by Django 3.2.6 on 2021-10-14 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0003_remove_switch_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testplan',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
