# Generated by Django 3.2.6 on 2021-10-02 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0003_auto_20211002_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='fixed',
            field=models.BooleanField(default=True),
        ),
    ]
