# Generated by Django 3.2.6 on 2021-09-21 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0003_auto_20210921_0504'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='configuration',
            table='Configuration',
        ),
        migrations.AlterModelTable(
            name='measure',
            table='Measures',
        ),
        migrations.AlterModelTable(
            name='measurement',
            table='Measurement',
        ),
    ]
