# Generated by Django 3.2.6 on 2021-09-25 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0005_auto_20210922_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='PModelCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('displayname', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'PModelCatalog',
            },
        ),
        migrations.AlterField(
            model_name='propagationmodel',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configurator.pmodelcatalog'),
        ),
        migrations.DeleteModel(
            name='PModel',
        ),
    ]
