# Generated by Django 3.2.6 on 2021-10-11 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0005_auto_20211003_0125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='max_queue_size',
            new_name='maxqueue',
        ),
    ]
