# Generated by Django 3.2.6 on 2021-09-26 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0006_auto_20210925_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='MModelCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('displayname', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'MModelCatalog',
            },
        ),
        migrations.CreateModel(
            name='MobilityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configurator.mmodelcatalog')),
            ],
            options={
                'db_table': 'MobilityModel',
            },
        ),
        migrations.CreateModel(
            name='MobilityParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('value', models.FloatField()),
                ('mobilitymodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configurator.mobilitymodel')),
            ],
            options={
                'db_table': 'MobilityParam',
            },
        ),
        migrations.AddField(
            model_name='configuration',
            name='mobilitymodel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configurator.mobilitymodel'),
        ),
    ]
