# Generated by Django 3.2.6 on 2021-10-11 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0006_rename_max_queue_size_link_maxqueue'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='accesspoint',
            name='node',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='configurator.node'),
        ),
        migrations.AlterField(
            model_name='host',
            name='node',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='configurator.node'),
        ),
        migrations.AlterField(
            model_name='station',
            name='node',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='configurator.node'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='node',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='configurator.node'),
        ),
    ]
