# Generated by Django 3.2.6 on 2021-09-27 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0006_auto_20210926_2052'),
        ('configurator', '0007_auto_20210926_1724'),
    ]

    operations = [
    ]
