# Generated by Django 3.2.6 on 2021-10-11 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0007_auto_20211011_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='connection',
        ),
        migrations.RemoveField(
            model_name='link',
            name='maxqueue',
        ),
        migrations.RemoveField(
            model_name='link',
            name='speedup',
        ),
        migrations.AddField(
            model_name='link',
            name='bw',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='max_queue_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='delay',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='jitter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='loss',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
