# Generated by Django 3.2.6 on 2021-09-27 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0008_merge_0006_auto_20210926_2052_0007_auto_20210926_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('fixo', models.BooleanField()),
                ('ip', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Interface',
            },
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixo', models.BooleanField()),
            ],
            options={
                'db_table': 'Network',
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('fixo', models.BooleanField()),
                ('mac', models.CharField(max_length=30)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configurator.network')),
            ],
            options={
                'db_table': 'Node',
            },
        ),
        migrations.AddField(
            model_name='configuration',
            name='start_time',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='stop_time',
            field=models.FloatField(null=True),
        ),
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configurator.node')),
            ],
            options={
                'db_table': 'Switch',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configurator.node')),
            ],
            options={
                'db_table': 'Station',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configurator.node')),
            ],
            options={
                'db_table': 'Position',
            },
        ),
        migrations.CreateModel(
            name='Mobility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempo', models.FloatField()),
                ('fixo', models.BooleanField()),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configurator.node')),
            ],
            options={
                'db_table': 'Mobility',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conexao', models.CharField(max_length=30)),
                ('fixo', models.BooleanField()),
                ('delay', models.CharField(max_length=30)),
                ('loss', models.CharField(max_length=30)),
                ('tamanho_maximo_fila', models.CharField(max_length=30)),
                ('jitter', models.CharField(max_length=30)),
                ('speedup', models.CharField(max_length=30)),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configurator.interface')),
            ],
            options={
                'db_table': 'Link',
            },
        ),
        migrations.AddField(
            model_name='interface',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configurator.node'),
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configurator.node')),
            ],
            options={
                'db_table': 'Host',
            },
        ),
        migrations.CreateModel(
            name='AccessPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssid', models.CharField(max_length=30)),
                ('modo', models.CharField(max_length=30)),
                ('channel', models.CharField(max_length=30)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configurator.node')),
            ],
            options={
                'db_table': 'AccessPoint',
            },
        ),
        migrations.AddField(
            model_name='configuration',
            name='network',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configurator.network'),
        ),
    ]
