# Generated by Django 3.2.6 on 2021-10-11 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0008_auto_20211011_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='network',
            name='fixed',
        ),
        migrations.AddField(
            model_name='network',
            name='adhoc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='network',
            name='fading_cof',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='network',
            name='noise_th',
            field=models.IntegerField(default=-91),
        ),
    ]
