# Generated by Django 3.2.6 on 2021-09-29 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0009_auto_20210927_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interface',
            name='fixo',
        ),
        migrations.RemoveField(
            model_name='link',
            name='fixo',
        ),
        migrations.RemoveField(
            model_name='mobility',
            name='fixo',
        ),
        migrations.RemoveField(
            model_name='node',
            name='fixo',
        ),
    ]
