# Generated by Django 3.2.6 on 2021-09-28 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0010_auto_20210928_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='configuration',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configurator.configuration'),
        ),
    ]
