# Generated by Django 3.2.6 on 2021-09-29 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0010_auto_20210929_2107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='conexao',
            new_name='connection',
        ),
        migrations.RenameField(
            model_name='link',
            old_name='tamanho_maximo_fila',
            new_name='max_queue_size',
        ),
        migrations.RemoveField(
            model_name='link',
            name='interface',
        ),
        migrations.AddField(
            model_name='link',
            name='int1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='int1', to='configurator.interface'),
        ),
        migrations.AddField(
            model_name='link',
            name='int2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='int2', to='configurator.interface'),
        ),
    ]
