# Generated by Django 3.2.6 on 2021-09-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0011_auto_20210929_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='testplan',
            name='author',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testplan',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
