# Generated by Django 3.2.6 on 2021-09-07 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(blank=True)),
            ],
            options={
                'db_table': 'Round',
            },
        ),
    ]
