# Generated by Django 3.2.6 on 2021-09-07 20:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('experimenter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='end',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='round',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='round',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
