# Generated by Django 3.2.6 on 2021-09-07 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experimenter', '0002_auto_20210907_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='status',
            field=models.CharField(default='STARTING', max_length=50),
        ),
    ]
