# Generated by Django 3.2.6 on 2021-09-15 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experimenter', '0003_round_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='status',
            field=models.CharField(default='WAITING', max_length=50),
        ),
    ]
