# Generated by Django 3.2.6 on 2021-09-26 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0005_version'),
        ('experimenter', '0004_alter_round_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configurator.version'),
        ),
    ]
